# Generated by Django 6.0.7 on 2026-07-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.IntegerField(choices=[('admin', 'ADMIN'), ('manager', 'MANAGER'), ('member', 'MEMBER')], default=2),
        ),
    ]
