# Generated by Django 6.0.7 on 2026-07-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('manager', 'MANAGER'), ('member', 'MEMBER')], default='member'),
        ),
    ]
